db:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable statement_cache_mode=describe'
  dbname: 'whatsnew'
  loglevel: 'warn'
faktory:
  url: 'tcp://faktory:faktory@localhost:7419'
  loglevel: 'info'
hnsw:
  server:
    target: '127.0.0.1:19530'
    tls_enabled: false
  index:
    name_prefix: 'whatsnew_'
    dim: 768
    ef_construction: 200
    m: 48
    max_elements: 100000
    seed: 42
    space_type: 'COSINE'
feed_scheduler:
  time_interval: '5m'
  jobs:
    - job_type: 'FeedFetcher'
      queue: 'wn_feed_fetcher'
  loglevel: 'info'
twitter_scheduler:
  time_interval: '5m'
  jobs:
    - job_type: 'TwitterScraper'
      queue: 'wn_twitter_scraper'
  loglevel: 'info'
gdelt_fetcher:
  time_interval: '5m'
  event_root_code_whitelist: []
  new_web_resource_jobs:
    - job_type: 'WebScraper'
      queue: 'wn_web_scraper'
  loglevel: 'info'
jobs_recoverer:
  time_interval: '1m'
  leeway_time: '1m'
  loglevel: 'info'
server:
  address: '0.0.0.0:10000'
  tls_enabled: false
  tls_cert: ''
  tls_key: ''
  allowed_origins: ['*']
  loglevel: 'info'
workers:
  feed_fetcher:
    queues: ['wn_feed_fetcher']
    concurrency: 10
    new_web_resource_jobs:
      - job_type: 'WebScraper'
        queue: 'wn_web_scraper'
    max_allowed_failures: 15
    omit_items_published_before:
      enabled: true
      time: '2021-07-01T00:00:00Z'
    language_filter: ['en', 'es', 'fr', 'it']
    loglevel: 'info'
  twitter_scraper:
    queues: ['wn_twitter_scraper']
    concurrency: 10
    max_tweets_number: 1000
    new_web_article_jobs:
      - job_type: 'Translator'
        queue: 'wn_translator'
    omit_tweets_published_before:
      enabled: true
      time: '2021-07-01T00:00:00Z'
    language_filter: ['en', 'es', 'fr', 'it']
    loglevel: 'info'
  web_scraper:
    queues: ['wn_web_scraper']
    concurrency: 10
    new_web_article_jobs:
      - job_type: 'Translator'
        queue: 'wn_translator'
    language_filter: ['en', 'es', 'fr', 'it']
    request_timeout: '30s'
    user_agent: 'WhatsNew/0.0.0'
    loglevel: 'info'
  translator:
    queues: ['wn_translator']
    concurrency: 4
    translator_server:
      target: '127.0.0.1:4557'
      tls_enabled: false
    processed_web_article_jobs:
      - job_type: 'ZeroShotClassifier'
        queue: 'wn_zero_shot_classifier'
    language_whitelist: ['fr', 'it']
    target_language: 'en'
    loglevel: 'info'
  zero_shot_classifier:
    queues: ['wn_zero_shot_classifier']
    concurrency: 4
    processed_web_article_jobs:
      - job_type: 'Vectorizer'
        queue: 'wn_vectorizer'
    spago_bart_server:
      target: '127.0.0.1:4001'
      tls_enabled: false
    hypothesis_template: 'This text is about {}.'
    possible_labels: ['sport', 'economy', 'science']
    multi_class: true
    loglevel: 'info'
  vectorizer:
    queues: ['wn_vectorizer']
    concurrency: 4
    vectorized_web_article_jobs:
      - job_type: 'DuplicateDetector'
        queue: 'wn_duplicate_detector'
    spago_bert_server:
      target: '127.0.0.1:1976'
      tls_enabled: false
    loglevel: 'info'
  duplicate_detector:
    queues: ['wn_duplicate_detector']
    timeframe_days: 3
    distance_threshold: 0.3
    non_duplicate_web_article_jobs:
      - job_type: 'InformationExtractor'
        queue: 'wn_information_extractor'
    duplicate_web_article_jobs: []
    loglevel: 'info'
  information_extractor:
    queues: ['wn_information_extractor']
    concurrency: 4
    spago_bert_server:
      target: '127.0.0.1:5831'
      tls_enabled: false
    items:
      - label: 'love'
        question: 'What do I love?'
        answer_regexp: '.+'
        threshold: 0.8
      - label: 'hate'
        question: 'What do I hate?'
        answer_regexp: '.+'
        threshold: 0.8
    processed_web_article_jobs: []
    loglevel: 'info'
