db:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable statement_cache_mode=describe'
  dbname: 'whatsnew'
  loglevel: 'warn'
faktory:
  url: 'tcp://faktory:faktory@localhost:7419'
  queues: ['default']
  loglevel: 'info'
feeds_scheduling:
  time_interval: '5m'
  jobs: ['FeedFetcher']
  loglevel: 'info'
workers:
  feed_fetcher:
    concurrency: 10
    new_web_resource_jobs: ['WebScraper']
    loglevel: 'info'
