db:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable statement_cache_mode=describe'
  dbname: 'whatsnew'
  loglevel: 'warn'
faktory:
  url: 'tcp://faktory:faktory@localhost:7419'
  queues: ['default']
  loglevel: 'info'
feed_scheduler:
  time_interval: '5m'
  jobs: ['FeedFetcher']
  loglevel: 'info'
gdelt_fetcher:
  time_interval: '5m'
  event_root_code_whitelist: []
  new_web_resource_jobs: ['WebScraper']
  loglevel: 'info'
workers:
  feed_fetcher:
    concurrency: 10
    new_web_resource_jobs: ['WebScraper']
    max_allowed_failures: 15
    omit_items_published_before:
      enabled: true
      time: '2021-07-01T00:00:00Z'
    language_filter: ['en', 'es']
    loglevel: 'info'
