db:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable statement_cache_mode=describe'
  dbname: 'whatsnew'
  loglevel: 'warn'
faktory:
  url: 'tcp://faktory:faktory@localhost:7419'
  queues: ['default']
