db:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable statement_cache_mode=describe'
  dbname: 'whatsnew'
  loglevel: 'warn'
faktory:
  url: 'tcp://faktory:faktory@localhost:7419'
  loglevel: 'info'
hnsw:
  server:
    target: '127.0.0.1:19530'
    tls_enabled: false
  index:
    name_prefix: 'whatsnew_'
    dim: 768
    ef_construction: 200
    m: 48
    max_elements: 100000
    seed: 42
    space_type: 'COSINE'
feed_scheduler:
  time_interval: '5m'
  jobs: ['FeedFetcher']
  loglevel: 'info'
twitter_scheduler:
  time_interval: '5m'
  jobs: ['TwitterScraper']
  loglevel: 'info'
gdelt_fetcher:
  time_interval: '5m'
  event_root_code_whitelist: []
  new_web_resource_jobs: ['WebScraper']
  loglevel: 'info'
jobs_recoverer:
  time_interval: '1m'
  leeway_time: '1m'
  loglevel: 'info'
workers:
  feed_fetcher:
    queues: ['wn_feed_fetcher']
    concurrency: 10
    new_web_resource_jobs: ['WebScraper']
    max_allowed_failures: 15
    omit_items_published_before:
      enabled: true
      time: '2021-07-01T00:00:00Z'
    language_filter: ['en', 'es']
    loglevel: 'info'
  twitter_scraper:
    queues: ['wn_twitter_scraper']
    concurrency: 10
    max_tweets_number: 1000
    new_web_article_jobs: ['ZeroShotClassifier']
    omit_tweets_published_before:
      enabled: true
      time: '2021-07-01T00:00:00Z'
    language_filter: ['en', 'es']
    loglevel: 'info'
  web_scraper:
    queues: ['wn_web_scraper']
    concurrency: 10
    new_web_article_jobs: ['ZeroShotClassifier']
    language_filter: ['en', 'es']
    request_timeout: '30s'
    user_agent: 'WhatsNew/0.0.0'
    loglevel: 'info'
  zero_shot_classifier:
    queues: ['wn_zero_shot_classifier']
    concurrency: 4
    classified_web_article_jobs: ['Vectorizer']
    spago_bart_server:
      target: '127.0.0.1:4001'
      tls_enabled: false
    hypothesis_template: 'This text is about {}.'
    possible_labels: ['sport', 'economy', 'science']
    multi_class: true
    loglevel: 'info'
  vectorizer:
    queues: ['wn_vectorizer']
    concurrency: 4
    vectorized_web_article_jobs: ['DuplicateDetector']
    spago_bert_server:
      target: '127.0.0.1:1976'
      tls_enabled: false
    loglevel: 'info'
  duplicate_detector:
    queues: ['wn_duplicate_detector']
    timeframe_days: 3
    distance_threshold: 0.3
    non_duplicate_web_article_jobs: []
    duplicate_web_article_jobs: []
    loglevel: 'info'
